#!/bin/bash

#echo "LED Script"
TEST_PATH=test_folder

AMBER_INDICATOR_BRIGHTNESS_PATH=/sys/class/leds/amber_indicator_brightness
AMBER_BRIGHTNESS=${1:- 500}
echo "AMBER BRIGHTNESS:" $AMBER_BRIGHTNESS

BUTTON_BACKLIGHTS_PATH=/sys/class/leds/button_backlights
BACKLIGHT_BRIGHTNESS=${2:- 500}
echo "BACKLIGHT BRIGHTNESS:" $BACKLIGHT_BRIGHTNESS

LCD_BACKLIGHT_PATH=/sys/class/backlight/backlight
LCD_BACKLIGHT_BRIGHTNESS=${3:- 100}
echo "LCD BACKLIGHT BRIGHTNESS:" $LCD_BACKLIGHT_BRIGHTNESS


AC_AUTO_LED_PATH=/sys/class/leds/ac_auto
AC_ENABLE_PATH=/sys/class/leds/ac_enable 
DEFROST_FRONT_PATH=/sys/class/leds/defrost_front
DEFROST_REAR_PATH=/sys/class/leds/defrost_rear
RECIRCULATE_PATH=/sys/class/leds/recirculate
INDICATOR_M_PATH=/sys/class/leds/indicator_m
INDICATOR_N_PATH=/sys/class/leds/indicator_n
INDICATOR_O_PATH=/sys/class/leds/indicator_o
INDICATOR_P_PATH=/sys/class/leds/indicator_p
INDICATOR_Q_PATH=/sys/class/leds/indicator_q
INDICATOR_R_PATH=/sys/class/leds/indicator_r
INDICATOR_S_PATH=/sys/class/leds/indicator_s



#cd $TEST_PATH
#mkdir new_dir
cd $LCD_BACKLIGHT_PATH
echo $LCD_BACKLIGHT_BRIGHTNESS > brightness



cd $AMBER_INDICATOR_BRIGHTNESS_PATH
echo $AMBER_BRIGHTNESS > brightness

cd $BUTTON_BACKLIGHTS_PATH
echo $BACKLIGHT_BRIGHTNESS > brightness

cd $AC_AUTO_LED_PATH
echo 1 > brightness

cd $AC_ENABLE_PATH
echo 1 > brightness
 
cd $DEFROST_FRONT_PATH
echo 1 > brightness

cd $DEFROST_REAR_PATH
echo 1 > brightness

cd $RECIRCULATE_PATH
echo 1 > brightness

cd $INDICATOR_M_PATH
echo 1 > brightness

cd $INDICATOR_N_PATH
echo 0 > brightness

cd $INDICATOR_O_PATH
echo 1 > brightness

cd $INDICATOR_P_PATH
echo 0 > brightness

cd $INDICATOR_Q_PATH
echo 1 > brightness

cd $INDICATOR_R_PATH
echo 0 > brightness

cd $INDICATOR_S_PATH
echo 1 > brightness 
